[GitHub Actions] Improve auto-mirror to SourceForge

diff --git a/.github/workflows/CI_windows.yml b/.github/workflows/CI_windows.yml
--- a/.github/workflows/CI_windows.yml
+++ b/.github/workflows/CI_windows.yml
@@ -271,16 +271,134 @@ jobs:
           tag_name: 'v${{ steps.next-semver.outputs.NEXT_SEMVER }}'
           name: '${{ steps.next-semver.outputs.NEXT_SEMVER }}'
           files: ./dl/artifacts/*/*.zip
-          draft: true
+          draft: false
           body_path: ./dl/artifacts/release_body.txt
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: 'Auto-Publish Release'
+      # **********************************************
+      # Mirror to SourceForge
+      # **********************************************
+      - name: 'Set up SourceForge Env'
         if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
-        uses: past-due/action-gh-release@master
-        with:
-          tag_name: 'v${{ steps.next-semver.outputs.NEXT_SEMVER }}'
-          name: '${{ steps.next-semver.outputs.NEXT_SEMVER }}'
-          draft: false
+        run: |
+          echo "SF_PROJECT_NAME=applocalconfig" >> $GITHUB_ENV
+          echo "SF_BASE_PATH=releases" >> $GITHUB_ENV
+      - name: 'Prepare SourceForge Config'
+        if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
+        id: sf-settings
+        working-directory: '${{ github.workspace }}'
+        run: |
+          RELEASE_TAG="v${{ steps.next-semver.outputs.NEXT_SEMVER }}"
+          echo "GITHUB_REPOSITORY is: ${GITHUB_REPOSITORY}"
+          echo "Release tag is: ${RELEASE_TAG}"
+        
+          if [[ $RELEASE_TAG == *..* ]]; then
+            # Reject any release tags with two ".." in a row
+            echo "::error ::Invalid RELEASE_TAG value - aborting."
+            exit 1
+          fi
+          if [ -z "${RELEASE_TAG}" ]; then
+            echo "::error ::RELEASE_TAG variable is empty. Aborting."
+            exit 1
+          fi
+
+          SF_FILE_PATH=""
+          if [ ! -z "${SF_BASE_PATH}" ]; then
+            SF_FILE_PATH="${SF_BASE_PATH}/"
+          fi
+          SF_FILE_PATH="${SF_FILE_PATH}${RELEASE_TAG}"
+          echo "SF_FILE_PATH=${SF_FILE_PATH}"
+          echo "::set-output name=SF_FILE_PATH::${SF_FILE_PATH}"
+
+          # Prepare release_assets directory
+          mkdir -p "release_assets/${SF_FILE_PATH}"
+      - name: 'Copy All Release Assets To SF Upload Dir'
+        if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
+        id: sf-stage-upload-dir
         env:
-         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SF_FILE_PATH: ${{ steps.sf-settings.outputs.SF_FILE_PATH }}
+        working-directory: 'dl/artifacts'
+        run: |
+          # Copy all release assets to upload dir
+          UPLOAD_DIR="${{ github.workspace }}/release_assets/${SF_FILE_PATH}"
+          for artifact in */*.zip ; do
+            echo "Found artifact: ${artifact}"
+            cp "${artifact}" "${UPLOAD_DIR}/$(basename -- "${artifact}")"
+          done
+          # Output list of staged files
+          cd "${UPLOAD_DIR}"
+          ls -al
+          echo "Done."
+      - name: Set up SourceForge known_hosts
+        if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
+        run: |
+          mkdir -p ~/.ssh/
+          # May need updating on occasion. See: https://sourceforge.net/p/forge/documentation/SSH%20Key%20Fingerprints/
+          # Output of: `ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts`
+          cat >> ~/.ssh/known_hosts << 'EOF'
+          frs.sourceforge.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOQD35Ujalhh+JJkPvMckDlhu4dS7WH6NsOJ15iGCJLC
+          frs.sourceforge.net ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2uifHZbNexw6cXbyg1JnzDitL5VhYs0E65Hk/tLAPmcmm5GuiGeUoI/B0eUSNFsbqzwgwrttjnzKMKiGLN5CWVmlN1IXGGAfLYsQwK6wAu7kYFzkqP4jcwc5Jr9UPRpJdYIK733tSEmzab4qc5Oq8izKQKIaxXNe7FgmL15HjSpatFt9w/ot/CHS78FUAr3j3RwekHCm/jhPeqhlMAgC+jUgNJbFt3DlhDaRMa0NYamVzmX8D47rtmBbEDU3ld6AezWBPUR5Lh7ODOwlfVI58NAf/aYNlmvl2TZiauBCTa7OPYSyXJnIPbQXg6YQlDknNCr0K769EjeIlAfY87Z4tw==
+          frs.sourceforge.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCwsY6sZT4MTTkHfpRzYjxG7mnXrGL74RCT2cO/NFvRrZVNB5XNwKNn7G5fHbYLdJ6UzpURDRae1eMg92JG0+yo=
+          EOF
+      - name: Set up SSH Agent
+        if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
+        env:
+          SF_KEY: ${{ secrets.SF_SSH_KEY }}
+        run: |
+          eval "$(ssh-agent -s)"
+          set +x
+
+          # Add the private key to SSH agent
+          mkdir -p ~/.ssh/
+          echo ${SF_KEY} | base64 --decode > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          ssh-add ~/.ssh/id_ed25519
+
+          # Create a public key file
+          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
+      - name: 'Mirror Release Assets to SourceForge'
+        if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
+        id: sf-upload
+        env:
+          SF_FRS_USERNAME: ${{ secrets.SF_FRS_USERNAME }}
+          SF_FILE_PATH: ${{ steps.sf-settings.outputs.SF_FILE_PATH }}
+        working-directory: '${{ github.workspace }}/release_assets'
+        run: |
+          if [ -z "${SF_FILE_PATH}" ]; then
+            echo "::error ::SF_FILE_PATH variable is empty. Aborting this step."
+            exit 1
+          fi
+
+          # Upload all release assets
+          rsync -e ssh -rvh --relative "${SF_FILE_PATH}/" "${SF_FRS_USERNAME}@frs.sourceforge.net:/home/frs/project/${SF_PROJECT_NAME}/" --delete
+          echo "Done."
+      - name: Set Default SourceForge Downloads
+        if: success() && (steps.config.outputs.AUTO_RELEASE == 'true')
+        env:
+          SF_RELEASES_API_KEY: ${{ secrets.SF_RELEASES_API_KEY }}
+          SF_FILE_PATH: ${{ steps.sf-settings.outputs.SF_FILE_PATH }}
+        working-directory: '${{ github.workspace }}/release_assets'
+        run: |
+          echo "The provided tagged release is, in fact, the latest release. Updating default downloads:"
+
+          if [ -z "${SF_RELEASES_API_KEY}" ]; then
+            echo "::error ::SF_RELEASES_API_KEY secret was not set. Aborting this step."
+            exit 1
+          fi
+
+          # User-defined function
+          set_sf_default_if_present(){
+            local filename="$1"
+          	local sf_default_string="$2"
+            if [ -f "${SF_FILE_PATH}/$filename" ]; then
+              echo "Setting: \"${SF_FILE_PATH}/${filename}\" as: ${sf_default_string}"
+              curl -H "Accept: application/json" -X PUT -d "${sf_default_string}" -d "api_key=${SF_RELEASES_API_KEY}" -s "https://sourceforge.net/projects/${SF_PROJECT_NAME}/files/${SF_FILE_PATH}/${filename}"
+            else
+              echo "::warning ::Did not find file: ${filename}"
+            fi
+          }
+
+          # Set default platform downloads for SourceForge
+          set_sf_default_if_present "applocalconfig-vc2019-x86.zip" "default=windows"
+
+          echo "Done."
